- name: Deploy a web application
  hosts: target*
  become: yes
  become_user: root
  tasks:
    - name: Install all required dependencies
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - "epel-release"
        - "python"
        - "python-devel"
        
    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml